version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
  
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_PASSWORD_FILE: ./mongo-auth.dev
    volumes:
      - db-data:/db-data

volumes:
  db-data: